繁体梗体中文（Java版）
lakejason0/mcwzh-meme-resourcepack pull request #204
Opened 2021-10-06 12:52 UTC by HornCopper

您好，BE已经有pr了，被推迟了
此处希望再次被推迟（？

2021-10-06 12:52 UTC, HornCopper commented
茶馆的人，加油，我看着

2021-10-06 12:54 UTC, XxLittleCxX requested changes
不是规范的模块

https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/wiki/%E6%A8%A1%E5%9D%97%E7%BB%93%E6%9E%84%E6%96%87%E6%A1%A3

2021-10-06 12:57 UTC, HornCopper commented
我认为这貌似不该作为模块，不过因为基岩版有人叫我这么做了然后就照搬（？

2021-10-06 12:58 UTC, XxLittleCxX requested changes
你是不是把整个繁体直接拉下来然后修改的。既然是模块了就直接把差异部分写进来，剩下的文本让构建来解决

2021-10-06 12:59 UTC, HornCopper commented
> > 我认为这貌似不该作为模块，不过因为基岩版有人叫我这么做了然后就照搬（？
> 
> 这挺难维护吧，等等其他人看法

如果有必要还是请加上推迟标签
虽然本人不是很愿意

2021-10-06 13:38 UTC, HornCopper commented
修改完畢（

2021-10-06 13:43 UTC, HornCopper commented
是這個意思沒錯了吧

2021-10-06 13:45 UTC, HornCopper commented on meme_resourcepack/pack.mcmeta
> +        {
這。。難道是數組嗎

2021-10-06 13:46 UTC, HornCopper commented on meme_resourcepack/pack.mcmeta
> +        {
等下我看看

2021-10-06 13:47 UTC, HornCopper commented on meme_resourcepack/pack.mcmeta
> +        {
改正√

2021-10-07 03:46 UTC, HornCopper commented
还请指明（

2021-10-16 08:12 UTC, merged